In [1]:
#q 5.3

In [2]:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)

In [3]:
factorial(28)/(factorial(16)*factorial(12))

30421755.0

In [4]:
#q 5.5.1

In [8]:
def MinNumCoins(m):
    if m==0:
        return 0
    if m==1:
        return 1
    if m==2:
        return 2
    if m==3:
        return 3
    if m==4:
        return 1
    if m>=5:
        return min(MinNumCoins(m-1)+1,MinNumCoins(m-4)+1,MinNumCoins(m-5)+1)

In [12]:
MinNumCoins(12)

3

In [15]:
ret=''
for i in range(13,23):
    ret=ret+str(MinNumCoins(i))+' '
ret

'3 3 3 4 4 4 4 4 5 5 '

In [16]:
#q 5.5.2

In [22]:
def dpchange(money,coins):
    MinNumCoins=[0]
    for m in range (1,money+1):
        MinNumCoins.append(10000)
        for i in range(0,len(coins)):
            if m >= coins[i]:
                if MinNumCoins[m-coins[i]]+1<MinNumCoins[m]:
                    MinNumCoins[m]=MinNumCoins[m-coins[i]]+1
    return MinNumCoins[money]

In [24]:
dpchange(17972,[22,5,3,1])

820

In [25]:
#q 5.6

In [87]:
import numpy as np
def ManhattanTourist(n, m, Down, Right):
    array=np.zeros(((n+1),(m+1)))
    for i in range(1,n+1):
        array[i,0] = array[i-1,0]+down[i-1,0]
    for j in range(1,m+1):
        array[0,j] = array[0,j-1]+right[0,j-1]
    for i in range(1,n+1):
        for j in range(1,m+1):
            array[i,j]=max(array[i-1,j]+down[i-1,j],array[i,j-1]+right[i,j-1])
    return array[n,m]

In [90]:
myfile= open("dataset_240301_10.txt", "r")
n=0
m=0
matr_num=0
drow=0
rrow=0
for line in myfile:
    if line.strip()=='-':
            matr_num=2
    if matr_num==1:
        new_row=line.strip().split(' ')
        down[drow,]=new_row
        drow+=1
    if matr_num==2 and line.strip()!='-':
        new_row=line.strip().split(' ')
        right[rrow,]=new_row
        rrow+=1
    if matr_num==0:
        st=line.strip()
        nm=st.split(' ')
        n=int(nm[0])
        m=int(nm[1])
        down=np.empty((n,m+1))
        right=np.empty((n+1,m))
        matr_num=1
ManhattanTourist(n, m, down, right)

45.0

In [273]:
#5.8.1

In [112]:
def LCSBackTrack(v, w):
    array=np.zeros(((len(v)+1),(len(w)+1)))
    Backtrack=np.zeros(((len(v)+1),(len(w)+1)))
    for i in range (1,len(v)+1):
        for j in range(1,len(w)+1):
            match=0
            if v[i-1]==w[j-1]:
                match=1
            array[i,j]=max(array[i-1,j],array[i,j-1],array[i-1,j-1]+match)
            if array[i,j]==array[i-1,j]:
                Backtrack[i,j]=1
            elif array[i,j]==array[i,j-1]:
                Backtrack[i,j]=2
            elif array[i,j]==array[i-1,j-1]+match:
                Backtrack[i,j]=3
    print(array)
    return Backtrack

In [237]:
backtrack=LCSBackTrack(v,w)
backtrack

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]


array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 3.]])

In [113]:
def OutputLCS(backtrack, v, i, j):
    if i==0 or j==0:
        return ''
    if backtrack[i,j]==1:
        return OutputLCS(backtrack, v, i - 1, j)
    elif backtrack[i,j]==2:
        return OutputLCS(backtrack, v, i, j - 1)
    elif backtrack[i,j]==3:
        return OutputLCS(backtrack, v, i - 1, j - 1) + v[i-1]

In [114]:
v='AACCTTGG'
w='ACACTGTGA'
backtrack=LCSBackTrack(v,w)
print(backtrack)
OutputLCS(backtrack, v, len(v), len(w))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 2. 2. 2. 2. 2. 2. 2.]
 [0. 1. 2. 2. 3. 3. 3. 3. 3. 3.]
 [0. 1. 2. 2. 3. 3. 3. 3. 3. 3.]
 [0. 1. 2. 2. 3. 4. 4. 4. 4. 4.]
 [0. 1. 2. 2. 3. 4. 4. 5. 5. 5.]
 [0. 1. 2. 2. 3. 4. 5. 5. 6. 6.]
 [0. 1. 2. 2. 3. 4. 5. 5. 6. 6.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 3. 2. 2. 2. 2. 2. 2. 2. 2.]
 [0. 1. 1. 3. 2. 2. 2. 2. 2. 2.]
 [0. 1. 3. 1. 3. 2. 2. 2. 2. 2.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 3. 2. 2. 2. 2.]
 [0. 1. 1. 1. 1. 1. 1. 3. 2. 2.]
 [0. 1. 1. 1. 1. 1. 3. 1. 3. 2.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


'AACTTG'

In [271]:
myfile= open("dataset_240303_5.txt", "r")
c=1
v=''
w=''
for line in myfile:
    if c==1:
        v=line.strip()
        c=2
    if c==2:
        w=line.strip()
len(v)<len(w)

True

In [272]:
backtrack=LCSBackTrack(v,w)
OutputLCS(backtrack, v, len(v), len(w))

[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   1.   1.   1.]
 [  0.   0.   1. ...   2.   2.   2.]
 ...
 [  0.   1.   2. ... 574. 574. 574.]
 [  0.   1.   2. ... 574. 574. 574.]
 [  0.   1.   2. ... 574. 574. 575.]]


'TCTAACTGTTGCGCCCACCGGATGAATTCATGGCAGGCGGCCTTTGTTAAGGGATGCCCGTCTCGGTCCCGCTAGAAAATTGTTCGCGGATAAGCTCAGCTGAGCCAGCATTAGCGAGGATCACGCTCCGGCTCAGCTGAGCCTGGGTGTTCTGTCTCGTCTAAGAAAAAGACAGTTGGGTAGACTTCTTGTGTATGATTGAAATGGTCCCCCCAGGAGTCAAGGTGAAGGAAGTCGGAGCCCCATAGGGGGTTGTCGGCGTCACATCAGGCGAGGATAGTAAGGGCTCCAGATTTGGTCGAACGAGGTTCCCCGTGCGGGTTTACACGTACCCTCTACACGTTAACCTCCCAATAACCTTACGACCCCAACGGTGATATCTCTTATAGGCAGCCGAAGCTGGGAACAATACCCGAAGATACAAGTAAAACCACGGTTGCTCTATTGTCGGATTGGCTGCCAACCTTTAGGTCCTCCCTAGCACAACCCCTTAGATGAACGGGGATTGGCAGTAATCTGAGAGAAACTTTTTGTAGTAAACCACTAATAAAAGGGCGCGAACACAAAGGACAGCG'

In [274]:
#5.8.2(wrong version)

In [52]:
myfile= open("dataset_240303_7.txt", "r")
c=1
start=''
end=''
dict={}
for line in myfile:
    if c==3:
        st=line.strip()
        st=st.replace('->',':')
        temp=st.split(':')
        dict[(temp[0],temp[1])]=int(temp[2])
    if c==2:
        end=line.strip()
        c=3
    if c==1:
        start=line.strip()
        c=2
end

'49'

In [53]:
paths=[]
weights=[]
for elem in dict:
    if elem[1]==end:
        paths=paths+[[elem[0],elem[1]]]
        weights=weights+[dict[elem]]
for i in range(1,20):
    for elem in dict:
        for path in paths:
            if elem[1]==path[0]:
                ind=paths.index(path)
                paths[ind]=[elem[0]]+path
                weights[ind]=weights[ind]+dict[elem]

print(paths)
weights

[['0', '1', '3', '6', '14', '25', '49'], ['0', '1', '3', '4', '13', '49'], ['0', '1', '24', '49'], ['0', '8', '49'], ['0', '8', '14', '49'], ['0', '1', '3', '4', '13', '43', '49'], ['0', '1', '3', '4', '5', '7', '9', '10', '11', '19', '47', '48', '49'], ['0', '1', '3', '6', '14', '33', '36', '44', '49']]


[62, 64, 22, 17, 33, 70, 128, 80]

In [54]:
max(weights)

128

In [55]:
weights.index(max(weights))

6

In [56]:
'->'.join(paths[6])

'0->1->3->4->5->7->9->10->11->19->47->48->49'

In [ ]:
#5.8.2(right)

In [ ]:
myfile= open("dataset_240303_7.txt", "r")
case=''
for line in myfile:
    case=case+line
case

In [61]:
import random


def parse_data(dataset): ##! read in the graph into some python object
  nodes = set()
  adj_list = {}
  rev_adj_list = {}
  for line in dataset: ##! just some data preprocesing
    line = line.strip().split("->")
    node1 = int(line[0])
    node2, weight = map(int, line[1].split(":"))
    nodes.add(node1)
    nodes.add(node2)
    adj_list.setdefault(node1, []).append((node2, weight))
    # store reverse edges to easily find previous nodes
    rev_adj_list.setdefault(node2, []).append((node1, weight))
  return sorted(nodes), adj_list, rev_adj_list


def solve(dataset):
  dataset = dataset.splitlines()
  start, end = map(int, dataset[:2])
  dataset = dataset[2:]
  ##! just read in graph. build nodes, and edges
  nodes, adj_list, _ = parse_data(dataset) 
  print('nodes')
  print (nodes)
  print('adj_list')
  print(adj_list)
  #
  dp = {n:-float("inf") for n in nodes}
  dp[start] = 0 ##! set 0 at the start
  prev = {}
  #
  ##! looks like greedy algorithm
  for node in nodes:
    for neigh, weight in adj_list.get(node, []): ##! go over each neighbor
      if dp[neigh] < dp[node] + weight: ##! if we gain "weight" then we keep the node
        dp[neigh] = dp[node] + weight
        prev[neigh] = node
  #
  prev_node = end
  path = []
  while prev_node is not None:
    path.append(prev_node)
    prev_node = prev.get(prev_node)
  #
  solution = "{}\n{}".format(dp[end], "->".join(map(str, path[::-1])))
  return solution


#### run testing

testcase = "0\n4\n0->1:7\n0->2:4\n2->3:2\n1->4:1\n3->4:3"

solve(case)

nodes
[0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
adj_list
{0: [(7, 9), (28, 6), (1, 6)], 7: [(12, 6), (33, 8), (28, 20), (35, 16)], 12: [(22, 1), (44, 9), (49, 3), (40, 14)], 22: [(49, 13), (33, 16)], 3: [(40, 6), (4, 15)], 38: [(44, 11), (46, 11), (43, 16)], 10: [(15, 20), (21, 20), (11, 10), (22, 10), (25, 5), (20, 2), (13, 5)], 20: [(40, 14)], 42: [(46, 10), (47, 6), (48, 8)], 19: [(21, 11), (34, 12), (39, 2)], 44: [(48, 9), (45, 15)], 13: [(29, 9), (27, 11), (14, 15)], 39: [(41, 3), (48, 8)], 36: [(38, 3), (42, 18)], 46: [(49, 13), (47, 4)], 28: [(31, 17), (45, 15), (43, 5)], 32: [(41, 6), (48, 13)], 37: [(44, 7)], 6: [(36, 12), (8, 3)], 9: [(34, 7), (15, 7), (10, 13)], 29: [(49, 8), (36, 15), (38, 14), (32, 12)], 11: [(23, 13)], 23: [(25, 20), (28, 16)], 35: [(38, 6), (43, 10), (48, 14)], 25: [(38, 13), (29, 15)], 27: [(30, 1), (45, 8), (36, 15),

'184\n0->1->3->4->6->8->9->10->11->23->25->29->36->38->44->45->47->49'

In [183]:
#5.10.1

In [226]:
import pandas as pd
import numpy as np
myfile= open("BLOSUM62.txt", "r")
c=1
cr_names=[]
scores=[]
for line in myfile:
    if c==2:
        st=line.strip().replace('  ',' ')
        scores=scores+st.split(' ')[1:]
    if c==1:
        cr_names=line.strip().split('  ')
        c=2
for i in range(len(scores)):
    scores[i]=int(scores[i])
scores_mat=matrix = np.reshape(scores, (20, 20))
scores_mat=pd.DataFrame(scores_mat, columns=cr_names, index=cr_names)
scores_mat

A  C  D  E  F  G  H  I  K  L  M  N  P  Q  R  S  T  V   W  Y
A  4  0 -2 -1 -2  0 -2 -1 -1 -1 -1 -2 -1 -1 -1  1  0  0  -3 -2
C  0  9 -3 -4 -2 -3 -3 -1 -3 -1 -1 -3 -3 -3 -3 -1 -1 -1  -2 -2
D -2 -3  6  2 -3 -1 -1 -3 -1 -4 -3  1 -1  0 -2  0 -1 -3  -4 -3
E -1 -4  2  5 -3 -2  0 -3  1 -3 -2  0 -1  2  0  0 -1 -2  -3 -2
F -2 -2 -3 -3  6 -3 -1  0 -3  0  0 -3 -4 -3 -3 -2 -2 -1   1  3
G  0 -3 -1 -2 -3  6 -2 -4 -2 -4 -3  0 -2 -2 -2  0 -2 -3  -2 -3
H -2 -3 -1  0 -1 -2  8 -3 -1 -3 -2  1 -2  0  0 -1 -2 -3  -2  2
I -1 -1 -3 -3  0 -4 -3  4 -3  2  1 -3 -3 -3 -3 -2 -1  3  -3 -1
K -1 -3 -1  1 -3 -2 -1 -3  5 -2 -1  0 -1  1  2  0 -1 -2  -3 -2
L -1 -1 -4 -3  0 -4 -3  2 -2  4  2 -3 -3 -2 -2 -2 -1  1  -2 -1
M -1 -1 -3 -2  0 -3 -2  1 -1  2  5 -2 -2  0 -1 -1 -1  1  -1 -1
N -2 -3  1  0 -3  0  1 -3  0 -3 -2  6 -2  0  0  1  0 -3  -4 -2
P -1 -3 -1 -1 -4 -2 -2 -3 -1 -3 -2 -2  7 -1 -2 -1 -1 -2  -4 -3
Q -1 -3  0  2 -3 -2  0 -3  1 -2  0  0 -1  5  1  0 -1 -2  -2 -1
R -1 -3 -2  0 -3 -2  0 -3  2 -2 -1  0 -2  1  5 -1 -1 -3  -3 -2
S  1 -1  0  0 -2  0 -1 -2  0 -2 -1  1 -1  0 -1  4  1 -2  -3 -2
T  0 -1 -1 -1 -2 -2 -2 -1 -1 -1 -1  0 -1 -1 -1  1  5  0  -2 -2
V  0 -1 -3 -2 -1 -3 -3  3 -2  1  1 -3 -2 -2 -3 -2  0  4  -3 -1
W -3 -2 -4 -3  1 -2 -2 -3 -3 -2 -1 -4 -4 -2 -3 -3 -2 -3  11  2
Y -2 -2 -3 -2  3 -3  2 -1 -2 -1 -1 -2 -3 -1 -2 -2 -2 -1   2  7

In [121]:
def LCSBackTrack(v, w):
    array=np.zeros(((len(v)+1),(len(w)+1)))
    Backtrack=np.zeros(((len(v)+1),(len(w)+1)))
    for i in range (0,len(v)+1):
        array[i,0]=0-i*5
    for j in range (0,len(w)+1):
        array[0,j]=0-j*5
    for i in range (1,len(v)+1):
        for j in range(1,len(w)+1):
            match=scores_mat[v[i-1]][w[j-1]]
            array[i,j]=max(array[i-1,j]-5,array[i,j-1]-5,array[i-1,j-1]+match)
            if array[i,j]==array[i-1,j]-5:
                Backtrack[i,j]=1
            elif array[i,j]==array[i,j-1]-5:
                Backtrack[i,j]=2
            elif array[i,j]==array[i-1,j-1]+match:
                Backtrack[i,j]=3
    print(array)
    return Backtrack

In [181]:
myfile= open("dataset_240305_3.txt", "r")
c=1
v=''
w=''
for line in myfile:
    if c==1:
        v=line.strip()
        c=2
    if c==2:
        w=line.strip()
backtrack=LCSBackTrack(v,w)
backtrack

[[    0.    -5.   -10. ... -4225. -4230. -4235.]
 [   -5.     5.     0. ... -4215. -4220. -4225.]
 [  -10.     0.    12. ... -4203. -4208. -4213.]
 ...
 [-4130. -4120. -4108. ...  1804.  1799.  1804.]
 [-4135. -4125. -4113. ...  1799.  1808.  1803.]
 [-4140. -4130. -4118. ...  1794.  1803.  1816.]]


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 3., 2., ..., 2., 2., 2.],
       [0., 1., 3., ..., 2., 2., 2.],
       ...,
       [0., 1., 1., ..., 3., 2., 1.],
       [0., 1., 1., ..., 1., 3., 2.],
       [0., 1., 1., ..., 1., 1., 3.]])

In [167]:
def OutputLCS(backtrack, v, w, i, j):
    if i==0 or j==0:
        return ('','')
    if backtrack[i,j]==1:
        reta,retb = OutputLCS(backtrack, v, w,i - 1, j)
        return (reta+ v[i-1],retb+ '-')
    elif backtrack[i,j]==2:
        reta,retb = OutputLCS(backtrack, v, w,i, j - 1)
        return (reta+ '-',retb+ w[j-1])
    elif backtrack[i,j]==3:
        reta,retb = OutputLCS(backtrack, v, w,i - 1, j - 1) 
        return (reta+ v[i-1],retb+ w[j-1])

In [182]:
OutputLCS(backtrack, v, w,len(v), len(w))

('KPSRGMEFGGF-----SFRR-Y-VCMHMWTRKWVHDVWNEWLMYLAREANGFLVKHGKSTAEIVRSHCHFSHMQDCMLDHGSVRVDCHIFYMWCNCLAFVAYDKNTQKPNQRTPKLRSMGFTMQFICC-DFN--RRYHAVVEQKMMSCTQTIY-------WQSQHDGSFHTDWMHMMIGEGAFLPHMCNMTMDAGSNFPPSPSDINEDKQQLVCHGRFLHLHNRKTSPPADCACPSMTNLIYWLRNCWMLG-HT--RNQD--M-KINIGEWYRATNWNNTCIHMALFDQAQMNWDKWTGWGNPRYGQTCDQECWIYRTGVGHSQAANLCYQCRSERCMNDRQQTCNPHTEYEATVREKWKHFVYAMWETEARPC-M-KCSKKLGCCYTYVNCYPPNY-HS-Q-E----V--SVKELHGYACWMSDPMQCSGVNDD------D--VKMRMGRW-G-----F--NNVHSWKWVSGMDMPYEKFGRWTVDPENARITQITGTRPMNEQNRSGIMESVTPHFTRWCFP-LSKRSYSIKH-TFKHTQKMCAFNGGGDRCAGHRSIVPR----D---PMEDCMKKKWKMFTADNRDNWYHYNRGLIGH-WSKFHGVKKNT---G-M--VGINPHAVC-S---WYISMCQE--G--CHTC-------SAQMGTKASMCQNVVYNNGMWWSVSSMMMVSLQDE-E---AQAFMREERWHLTFWGEHYYTSLGGDEPKIPSMYIQYREE----LC-H-G-----YEC--F---HNKDLKHTFCNHL----L----C-RVLRFHNKSKQQNIKFNPRQEVLKQCS--K--WHF--N-TAETHRWRIYIFRNDIDCFWFNKW-CRGPFTFQWNARFSL-LFN---VLKQE-DSNCSIFACIDLLSCTGQWCRFTGCEPDAWQSHWVTNEKSYDKNWFTDLKPPAQSIDFRHGDSALTHSMIH',
 'KPSRGMEFGGWNDDIGSFRMAWEIPM-MWTRKNVTNGRMRWL

In [185]:
#5.10.2

In [227]:
import pandas as pd
import numpy as np
myfile= open("PAM250.txt", "r")
c=1
cr_names=[]
scores=[]
for line in myfile:
    if c==2:
        st=line.strip().replace('  ',' ')
        scores=scores+st.split(' ')[1:]
    if c==1:
        cr_names=line.strip().split('  ')
        c=2
for i in range(len(scores)):
    scores[i]=int(scores[i])
scores_mat=matrix = np.reshape(scores, (20, 20))
scores_mat=pd.DataFrame(scores_mat, columns=cr_names, index=cr_names)
scores_mat

A   C  D  E  F  G  H  I  K  L  M  N  P  Q  R  S  T  V   W   Y
A  2  -2  0  0 -3  1 -1 -1 -1 -2 -1  0  1  0 -2  1  1  0  -6  -3
C -2  12 -5 -5 -4 -3 -3 -2 -5 -6 -5 -4 -3 -5 -4  0 -2 -2  -8   0
D  0  -5  4  3 -6  1  1 -2  0 -4 -3  2 -1  2 -1  0  0 -2  -7  -4
E  0  -5  3  4 -5  0  1 -2  0 -3 -2  1 -1  2 -1  0  0 -2  -7  -4
F -3  -4 -6 -5  9 -5 -2  1 -5  2  0 -3 -5 -5 -4 -3 -3 -1   0   7
G  1  -3  1  0 -5  5 -2 -3 -2 -4 -3  0  0 -1 -3  1  0 -1  -7  -5
H -1  -3  1  1 -2 -2  6 -2  0 -2 -2  2  0  3  2 -1 -1 -2  -3   0
I -1  -2 -2 -2  1 -3 -2  5 -2  2  2 -2 -2 -2 -2 -1  0  4  -5  -1
K -1  -5  0  0 -5 -2  0 -2  5 -3  0  1 -1  1  3  0  0 -2  -3  -4
L -2  -6 -4 -3  2 -4 -2  2 -3  6  4 -3 -3 -2 -3 -3 -2  2  -2  -1
M -1  -5 -3 -2  0 -3 -2  2  0  4  6 -2 -2 -1  0 -2 -1  2  -4  -2
N  0  -4  2  1 -3  0  2 -2  1 -3 -2  2  0  1  0  1  0 -2  -4  -2
P  1  -3 -1 -1 -5  0  0 -2 -1 -3 -2  0  6  0  0  1  0 -1  -6  -5
Q  0  -5  2  2 -5 -1  3 -2  1 -2 -1  1  0  4  1 -1 -1 -2  -5  -4
R -2  -4 -1 -1 -4 -3  2 -2  3 -3  0  0  0  1  6  0 -1 -2   2  -4
S  1   0  0  0 -3  1 -1 -1  0 -3 -2  1  1 -1  0  2  1 -1  -2  -3
T  1  -2  0  0 -3  0 -1  0  0 -2 -1  0  0 -1 -1  1  3  0  -5  -3
V  0  -2 -2 -2 -1 -1 -2  4 -2  2  2 -2 -1 -2 -2 -1  0  4  -6  -2
W -6  -8 -7 -7  0 -7 -3 -5 -3 -2 -4 -4 -6 -5  2 -2 -5 -6  17   0
Y -3   0 -4 -4  7 -5  0 -1 -4 -1 -2 -2 -5 -4 -4 -3 -3 -2   0  10

In [230]:
def LCSBackTrack(v, w):
    array=np.zeros(((len(v)+1),(len(w)+1)))
    Backtrack=np.zeros(((len(v)+1),(len(w)+1)))
    for i in range (0,len(v)+1):
        array[i,0]=0-i*5
    for j in range (0,len(w)+1):
        array[0,j]=0-j*5
    for i in range (1,len(v)+1):
        for j in range(1,len(w)+1):
            match=scores_mat[v[i-1]][w[j-1]]
            array[i,j]=max(array[i-1,j]-5,array[i,j-1]-5,array[i-1,j-1]+match,0)
            if array[i,j]==array[i-1,j]-5:
                Backtrack[i,j]=1
            elif array[i,j]==array[i,j-1]-5:
                Backtrack[i,j]=2
            elif array[i,j]==array[i-1,j-1]+match:
                Backtrack[i,j]=3
    return Backtrack,array

In [253]:
myfile= open("dataset_240305_10.txt", "r")
c=1
v=''
w=''
for line in myfile:
    if c==1:
        v=line.strip()
        c=2
    if c==2:
        w=line.strip()
backtrack,lengths=LCSBackTrack(v,w)
print(backtrack)
print(lengths)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 3. ... 3. 0. 0.]
 ...
 [0. 0. 3. ... 1. 1. 1.]
 [0. 0. 3. ... 1. 3. 1.]
 [0. 0. 3. ... 3. 1. 3.]]
[[ 0.000e+00 -5.000e+00 -1.000e+01 ... -4.445e+03 -4.450e+03 -4.455e+03]
 [-5.000e+00  0.000e+00  0.000e+00 ...  0.000e+00  0.000e+00  0.000e+00]
 [-1.000e+01  0.000e+00  1.000e+00 ...  2.000e+00  0.000e+00  0.000e+00]
 ...
 [-4.490e+03  0.000e+00  0.000e+00 ...  1.158e+03  1.159e+03  1.166e+03]
 [-4.495e+03  0.000e+00  0.000e+00 ...  1.153e+03  1.158e+03  1.161e+03]
 [-4.500e+03  0.000e+00  0.000e+00 ...  1.149e+03  1.153e+03  1.160e+03]]


In [254]:
maxElement = np.amax(lengths)
result = np.where(lengths == np.amax(lengths))
print(maxElement)
print(result)

1176.0
(array([894]), array([889]))


In [255]:
def OutputLCS(backtrack, v, w, i, j):
    if backtrack[i,j]==0:
        return ('','')
    if backtrack[i,j]==1:
        reta,retb = OutputLCS(backtrack, v, w,i - 1, j)
        return (reta+ v[i-1],retb+ '-')
    elif backtrack[i,j]==2:
        reta,retb = OutputLCS(backtrack, v, w,i, j - 1)
        return (reta+ '-',retb+ w[j-1])
    elif backtrack[i,j]==3:
        reta,retb = OutputLCS(backtrack, v, w,i - 1, j - 1) 
        return (reta+ v[i-1],retb+ w[j-1])

OutputLCS(backtrack, v, w,894, 889)

('NNWHLLIGSLCHHCQY-YTCS--EAHKQFEVTG-YMTVGGTVC-WREGFW-G-DNTDKSFKL--CEHVTWSLLPTC-DK-PMKAVE--DVEI-DS-RAVGTIQPRETLM-RAHYTTCMRSYLIFEDHDIEGQAD-DFRWGAKVAYE-QLYWFDNYSCQIMCEWLIQMMYAFRPGKDYFTAWAYHHNDYNKPFIHCWEN-EWDSDEEHPNIDLTFCQFRCPKSRECINKAAGSTAFNLIPWDNHFVPPKFFPHHETFIVTWQ--LLHCSGDA--GRIS--WELTQMIFNHPYQYGRSQANRTGVCNSVTSNFIMTSRHGMDFIYYTLNWPISPWVHKPLELWNVQNSCEYATCEECRVHCMKNIDPDRTAGDAPSYEKVDSPAFYVDVCKANKKIYAASLCKFN-LF-IGQTADHNYAW--Q-MP---FITFQHNQRQCWND-WCITVAQEYHAWPMWNYDRVGWWARIRPDGIDERYKQSTIYIVETPCEYQCTTCSVEGKYTATWRQMALNWMM-KHE-PC---KAKFERLWSTQEMELCGP---MM----KRNITVMRFGHSCCPKEGVQYF--GE---RCRSLYCMCHSFKENPLFFMKSHLQTTHGDYWHFFTWS-GHSWDN-----LMA-H--S-SYQCKAQIEANLVVW--CAQAFQRQEAIEAIW-QMAT-FL-GHLSLMS-YKMYMVHPYAHSNE-SFFHSEFANY-MDDLDPATQYVY-GW-LCCFRLGANQGLIPGSMYQ-PIMLIHSVMWGCCDATC-SCKG--TLAWLQPKNLCFPIW-CK-EQ-KSQK-DGYKA-FALIKS-WMCVL-RYTLVFTMHCYYMIDF-LITEQERDPIKECPCW-L-MPEGKASIIIQ-NPRESIRF-VEY-DSIR-WRPYELELTH-MSPRMNKMW-YMRHKF-NEEFGGFTPGYKYDACFNRLVYFYIKKWSSGFARGTPTSQTNGEEGRCDSCHFGQPDMGD-FHEAMQHWKH',
 'SGWGG-P

In [217]:
#5.11.1

In [75]:
# A Dynamic Programming based Python program for edit 
# distance problem 
def editDistDP(str1, str2, m, n): 
    # Create a table to store results of subproblems 
    dp = [[0 for x in range(n + 1)] for x in range(m + 1)] 
  
    # Fill d[][] in bottom up manner 
    for i in range(m + 1): 
        for j in range(n + 1): 
  
            # If first string is empty, only option is to 
            # insert all characters of second string 
            if i == 0: 
                dp[i][j] = j    # Min. operations = j 
  
            # If second string is empty, only option is to 
            # remove all characters of second string 
            elif j == 0: 
                dp[i][j] = i    # Min. operations = i 
  
            # If last characters are same, ignore last char 
            # and recur for remaining string 
            elif str1[i-1] == str2[j-1]: 
                dp[i][j] = dp[i-1][j-1] 
  
            # If last character are different, consider all 
            # possibilities and find minimum 
            else: 
                dp[i][j] = 1 + min(dp[i][j-1],        # Insert 
                                   dp[i-1][j],        # Remove 
                                   dp[i-1][j-1])    # Replace 
  
    return dp[m][n] 

In [76]:
myfile= open("dataset_240306_3.txt", "r")
str1=''
str2=''
c=1
for line in myfile:
    if c==1:
        str1=line.strip()
        c=2
    if c==2:
        str2=line.strip()
len(str1)>len(str2)

True

In [77]:
editDistDP(str1, str2, len(str1), len(str2))

355

In [186]:
#5.11.2

In [282]:
def LCSBackTrack(v, w):
    array=np.zeros(((len(v)+1),(len(w)+1)))
    Backtrack=np.zeros(((len(v)+1),(len(w)+1)))
    for i in range (0,len(v)+1):
        array[i,0]=0-i
    for i in range (1,len(v)+1):
        for j in range(1,len(w)+1):
            match=-1
            if v[i-1]==w[j-1]:
                match=1
            array[i,j]=max(array[i-1,j]-1,array[i,j-1]-1,array[i-1,j-1]+match)
            if array[i,j]==array[i-1,j]-1:
                Backtrack[i,j]=1
            elif array[i,j]==array[i,j-1]-1:
                Backtrack[i,j]=2
            elif array[i,j]==array[i-1,j-1]+match:
                Backtrack[i,j]=3
    return Backtrack,array

In [283]:
myfile= open("dataset_240306_5.txt", "r")
c=1
v=''
w=''
for line in myfile:
    if c==1:
        v=line.strip()
        c=2
    if c==2:
        w=line.strip()
backtrack,array=LCSBackTrack(w,v)
print(backtrack)
print(array)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 3. 2. ... 1. 1. 1.]
 [0. 1. 3. ... 3. 2. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 1. 1. ... 1. 1. 1.]
 [0. 1. 1. ... 1. 1. 1.]]
[[  0.   0.   0. ...   0.   0.   0.]
 [ -1.   1.   0. ...  -1.  -1.  -1.]
 [ -2.   0.   2. ...   0.  -1.  -2.]
 ...
 [-80. -78. -76. ...   3.   4.   6.]
 [-81. -79. -77. ...   2.   3.   5.]
 [-82. -80. -78. ...   1.   2.   4.]]


In [284]:
maxElement = max(array[len(w)])
result = np.where(array[len(w)]==maxElement)
print(maxElement)
result

16.0


(array([912]),)

In [280]:
def OutputLCS(backtrack, v, w, i, j):
    if i==0 or j==0:
        return ('','')
    if backtrack[i,j]==1:
        reta,retb = OutputLCS(backtrack, v, w,i - 1, j)
        return (reta+ v[i-1],retb+ '-')
    elif backtrack[i,j]==2:
        reta,retb = OutputLCS(backtrack, v, w,i, j - 1)
        return (reta+ '-',retb+ w[j-1])
    elif backtrack[i,j]==3:
        reta,retb = OutputLCS(backtrack, v, w,i - 1, j - 1) 
        return (reta+ v[i-1],retb+ w[j-1])

In [285]:
OutputLCS(backtrack, w, v, len(w), 912)

('TCACATGCCAA--CCTGGCCTTT-A-ACAGCTCATTTTGG-TCCTATTGC--GCATACTG-TT--GCTACAAAGGCCAACTACGTCGTATTT',
 'TCACAAGCCATTTCCTGGACAGTCATAC-GC-CGC---GGCTCTTATTTCCTG-ATAATGGTTATG-TCCACTG-CTA--TACCTT-TATAT')

In [187]:
#5.12

In [204]:
def LCSBackTrack(v, w):
    array=np.zeros(((len(v)+1),(len(w)+1)))
    Backtrack=np.zeros(((len(v)+1),(len(w)+1)))
    for i in range (0,len(v)+1):
        if i==0:
            array[i,0]=0
        elif i==1:
            array[i,0]=0-11
        else:
            array[i,0]=0-11-(i-1)
    for j in range (0,len(w)+1):
        if j==0:
            array[0,j]=0
        elif j==1:
            array[0,j]=0-11
        else:
            array[0,j]=0-11-(j-1)
    for i in range (1,len(v)+1):
        for j in range(1,len(w)+1):
            match=scores_mat[v[i-1]][w[j-1]]
            downPenal=11
            if Backtrack[i-1,j]==1:
                downPenal=1
            rightPenal=11
            if Backtrack[i,j-1]==2:
                rightPenal=1
            array[i,j]=max(array[i-1,j]-downPenal,array[i,j-1]-rightPenal,array[i-1,j-1]+match)
            if array[i,j]==array[i-1,j]-downPenal:
                Backtrack[i,j]=1
            elif array[i,j]==array[i,j-1]-rightPenal:
                Backtrack[i,j]=2
            elif array[i,j]==array[i-1,j-1]+match:
                Backtrack[i,j]=3
    print(array)
    return Backtrack

In [210]:
myfile= open("dataset_240307_8.txt", "r")
c=1
v=''
w=''
for line in myfile:
    if c==1:
        v=line.strip()
        c=2
    if c==2:
        w=line.strip()
backtrack=LCSBackTrack(v,w)
backtrack

[[  0. -11. -12. ... -87. -88. -89.]
 [-11.   6.  -5. ... -80. -81. -82.]
 [-12.  -5.  14. ... -71. -72. -73.]
 ...
 [-81. -74. -65. ... 332. 321. 320.]
 [-82. -75. -66. ... 321. 338. 327.]
 [-83. -76. -67. ... 320. 327. 342.]]


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 3., 2., ..., 2., 2., 2.],
       [0., 1., 3., ..., 2., 2., 2.],
       ...,
       [0., 1., 1., ..., 3., 2., 2.],
       [0., 1., 1., ..., 1., 3., 2.],
       [0., 1., 1., ..., 1., 1., 3.]])

In [207]:
def OutputLCS(backtrack, v, w, i, j):
    if i==0 or j==0:
        return ('','')
    if backtrack[i,j]==1:
        reta,retb = OutputLCS(backtrack, v, w,i - 1, j)
        return (reta+ v[i-1],retb+ '-')
    elif backtrack[i,j]==2:
        reta,retb = OutputLCS(backtrack, v, w,i, j - 1)
        return (reta+ '-',retb+ w[j-1])
    elif backtrack[i,j]==3:
        reta,retb = OutputLCS(backtrack, v, w,i - 1, j - 1) 
        return (reta+ v[i-1],retb+ w[j-1])

In [211]:
OutputLCS(backtrack, v, w,len(v), len(w))

('GHFPYQSMGKYLYNKNEP----RGSLMNTIAWAEETCYAYLRSWFVGWMFIIQWAGACLGFK---NGAIWWLCPYGKNDV',
 'GHFPYQSMGKYLYNSNEPVICGPRCPMNTIAWAEECCYAYLRSWFVGWMFILQWAG-CLGFKDMINGAIWWLCDYGKNDV')

In [251]:
len('Y-P-MSRKTAKSQFIEWCDW-F--CFNHWTNWAPLSIVRTSVAFAV-W-GHCWYPCG-GVCKTNRCKDD-FCGRWRKALFAEGPRDWKCCKNDLQNWNPQYSQGTR--NTK-RMVATTNQTMIEWKQSHIFETW-LF-CHVIIEYNWSAF-W-MWMNRNEAFNSIIKSGYPKLLL-T-QY-P-L-SQG--STPIVKPL-IRRD-QGKFW-A-WAQMWWFREPT-NIPTA-D-Y-CHSW--WQ--SR-ADLQ-NDRDMGP-EADASFYVEFWYWVRCAARTYGQQLGIIWNNRLKTRNPCPYSADGIQNKENYVFWWKNMCTKSHIAFYYCLQNVAHYTHDVTAEFNPVKCIDWLQGHMVLSSWFKYNTECKKLFVHEKCECYRM----FCGV---VEDIFGVRFH--TGWKHLSTAKPVPHVCVYNPSVQERRNINDFYIF-YEIAPAVKNLVLSAQPLHDYTKKCAFNYTPITITRIISTRNQIIW-AHVVIACQFYSPHQMLLIELAMDKYCADMNVRRSTEGHQPMHACRSTFGPGMAAKEPLVTFTLVAFWQWPNHEFQYVYMYTED-KIIQIG-PHLSN-GCEMVEYCVDC-YAK-RPCYRAYSAEAQYWRMITEAEDYSYKTRNAIAATATVRGQ-YCHPFRWLGIVWM-AHHDC-FFANECGTICI-PQMAEMRPPETTPYEI--DIIFMMF-WKE--HMSTTIL-DVVGMYRP-ATFSHWHDAHH-QCEPYLTPL-MCQSKLVFDAAFT--QVG-VKGVW-YHTEKLELMAGFNHM-K-FKKEEAQ---QSCFYWFQDCPDYDPPDAVRKTDEKHIRAHGEIWWLMRYYCMYHILHI-ASRHEWMHLRWDQACTNPGY--ELFE-F')

874

In [252]:
len('GLEY-P-MSRKTAKSQFIEWCDW-F--CFNHWTNWAPLSIVRTSVAFAV-W-GHCWYPCG-GVCKTNRCKDD-FCGRWRKALFAEGPRDWKCCKNDLQNWNPQYSQGTR--NTK-RMVATTNQTMIEWKQSHIFETW-LF-CHVIIEYNWSAF-W-MWMNRNEAFNSIIKSGYPKLLL-T-QY-P-L-SQG--STPIVKPL-IRRD-QGKFW-A-WAQMWWFREPT-NIPTA-D-Y-CHSW--WQ--SR-ADLQ-NDRDMGP-EADASFYVEFWYWVRCAARTYGQQLGIIWNNRLKTRNPCPYSADGIQNKENYVFWWKNMCTKSHIAFYYCLQNVAHYTHDVTAEFNPVKCIDWLQGHMVLSSWFKYNTECKKLFVHEKCECYRM----FCGV---VEDIFGVRFH--TGWKHLSTAKPVPHVCVYNPSVQERRNINDFYIF-YEIAPAVKNLVLSAQPLHDYTKKCAFNYTPITITRIISTRNQIIW-AHVVIACQFYSPHQMLLIELAMDKYCADMNVRRSTEGHQPMHACRSTFGPGMAAKEPLVTFTLVAFWQWPNHEFQYVYMYTED-KIIQIG-PHLSN-GCEMVEYCVDC-YAK-RPCYRAYSAEAQYWRMITEAEDYSYKTRNAIAATATVRGQ-YCHPFRWLGIVWM-AHHDC-FFANECGTICI-PQMAEMRPPETTPYEI--DIIFMMF-WKE--HMSTTIL-DVVGMYRP-ATFSHWHDAHH-QCEPYLTPL-MCQSKLVFDAAFT--QVG-VKGVW-YHTEKLELMAGFNHM-K-FKKEEAQ---QSCFYWFQDCPDYDPPDAVRKTDEKHIRAHGEIWWLMRYYCMYHILHI-ASRHEWMHLRWDQACTNPGY--ELFE-F')

877

In [1]:
myfile= open("reads_hw2undergrad_E_2_chr_1.txt", "r")
count=0
for line in myfile:
    count+=1
print(count)

300001
